Repository AxonIQ/axon-server-se, pull requests merged in 2019-05, with the labels that each got.

#7 Separate class for reserving sequence numbers
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/EventStorageEngine.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/EventWriteStorage.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/LocalEventStore.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/SerializedEvent.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/SerializedEventWithToken.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/SnapshotWriteStorage.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/SyncStorage.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/EventByteBufferIterator.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/EventInformation.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/EventIterator.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/IndexManager.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/InputStreamEventIterator.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/InputStreamEventStore.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/PrimaryEventStore.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/SegmentBasedEventStore.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/transaction/SequenceNumberCache.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/transaction/SingleInstanceTransactionManager.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/transaction/StorageTransactionManager.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/transformation/ProcessedEvent.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/transformation/WrappedEvent.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/FakeEventStore.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/LocalEventStorageEngineTest.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/file/InputStreamEventStoreTest.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/file/PrimaryEventStoreTest.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/transaction/SequenceNumberCacheTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/command/CommandCacheTest.java
  axonserver/src/test/java/io/axoniq/axonserver/rest/HttpStreamingQueryTest.java
  axonserver/src/test/java/io/axoniq/axonserver/util/ChangeableClock.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#10 Feature/tag based node selection strategy
  axonserver/src/main/java/io/axoniq/axonserver/component/tags/ClientTagsCache.java
  axonserver/src/main/java/io/axoniq/axonserver/component/tags/ClientTagsUpdate.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/PlatformService.java
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#14 gitignore data/
  .gitignore
Labels: Priority 4: Would, Status Resolved, Type: Enhancement

#16 [#15] Remove first resources block
  axonserver/pom.xml
Labels: Priority 4: Would, Status Resolved, Type: Enhancement

#21 Added sonatype snapshots repository
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Feature
