Repository AxonIQ/axon-server-se, pull requests merged in 2019-06, with the labels that each got.

#20 Allow for multiple grpc messages to be in transit for the same request
  axonserver/pom.xml
  axonserver/src/main/java/io/axoniq/axonserver/config/MessagingPlatformConfiguration.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/Gateway.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/GrpcBufferingInterceptor.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/GatewayTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/GrpcBufferingInterceptorTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/command/CommandDispatcherTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/QueryDispatcherTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#26 Index manager fixes
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/IndexManager.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/PositionInfo.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/file/IndexManagerTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#28 Rest access control
  axonserver/src/main/java/io/axoniq/axonserver/AxonServerAccessController.java
  axonserver/src/main/java/io/axoniq/axonserver/AxonServerStandardAccessController.java
  axonserver/src/main/java/io/axoniq/axonserver/rest/WebSecurityConfiguration.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/GatewayTest.java
  axonserver/src/test/java/io/axoniq/axonserver/rest/WebSecurityConfigurationTest.java
Labels: Priority 1: Must, Type: Bug

#29 bug/update_path_mapping
  axonserver/src/main/resources/db/migration/v1_14__path_mappings_update.sql
Labels: Type: Bug
