Repository AxonIQ/axon-server-se, pull requests merged in 2019-11, with the labels that each got.

#55 CORS settings needed for WebSocket in Axon Server UI
  axonserver/src/main/java/io/axoniq/axonserver/config/MessagingPlatformConfiguration.java
  axonserver/src/main/java/io/axoniq/axonserver/rest/WebSocketConfig.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#65 Instruction result
  axonserver/src/main/java/io/axoniq/axonserver/config/AxonServerStandardConfiguration.java
  axonserver/src/main/java/io/axoniq/axonserver/exception/ErrorCode.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/CommandService.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/DefaultInstructionAckSource.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/InstructionAckSource.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/PlatformService.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/QueryService.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/SerializedCommandProviderInbound.java
  axonserver/src/main/java/io/axoniq/axonserver/message/command/DirectCommandHandler.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/CommandServiceTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/PlatformServiceTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/QueryServiceTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/SerializedCommandProviderInboundTest.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#67 Delete context without data
  axonserver-cli/pom.xml
  axonserver-cli/src/main/java/io/axoniq/cli/CommandOptions.java
  axonserver-cli/src/main/java/io/axoniq/cli/DeleteNodeFromContext.java
  axonserver/src/main/java/io/axoniq/axonserver/config/AxonServerStandardConfiguration.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/PlatformService.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/EventStoreExistChecker.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/EventStoreFactory.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/LocalEventStore.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/DatafileEventStoreExistChecker.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/LowMemoryEventStoreFactory.java
  axonserver/src/main/java/io/axoniq/axonserver/message/event/LocalEventStoreHealthIndicator.java
  axonserver/src/main/java/io/axoniq/axonserver/rest/svg/mapping/Applications.java
  axonserver/src/main/java/io/axoniq/axonserver/topology/Topology.java
  axonserver/src/main/resources/static/applications.html
  axonserver/src/main/resources/static/context.html
  axonserver/src/main/resources/static/css/style.css
  axonserver/src/main/resources/static/users.html
  axonserver/src/main/vuejs/components/component/Processors.vue
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/LocalEventStorageEngineTest.java
  axonserver/src/test/java/io/axoniq/axonserver/rest/HttpStreamingQueryTest.java
Labels: Priority 1: Must
