Repository AxonIQ/axon-server-se, pull requests merged in 2020-04, with the labels that each got.

#91 Feature/insecure cli connections
  axonserver-cli/src/main/java/io/axoniq/cli/AxonIQCliCommand.java
  axonserver-cli/src/main/java/io/axoniq/cli/CommandOptions.java
Labels: Priority 2: Should, Status: In Progress

#100 Concurrency fixes
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/LocalEventStore.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/TrackingEventProcessorManager.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/query/QueryEventsRequestStreamObserver.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/TrackingEventProcessorManagerTest.java
  axonserver/src/test/java/io/axoniq/axonserver/rest/HttpStreamingQueryTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#99 Scheduled events
  axonserver-test-utils/pom.xml
  axonserver-test-utils/src/main/java/io/axoniq/axonserver/test/AssertUtils.java
  axonserver-test-utils/src/main/java/io/axoniq/axonserver/test/FakeClock.java
  axonserver-test-utils/src/main/java/io/axoniq/axonserver/test/FakeScheduledExecutorService.java
  axonserver-test-utils/src/main/java/io/axoniq/axonserver/test/FakeStreamObserver.java
  axonserver-test-utils/src/main/java/io/axoniq/axonserver/test/TestUtils.java
  axonserver/pom.xml
  axonserver/src/main/java/io/axoniq/axonserver/config/AxonServerStandardConfiguration.java
  axonserver/src/main/java/io/axoniq/axonserver/exception/ErrorCode.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/GrpcExceptionBuilder.java
  axonserver/src/main/java/io/axoniq/axonserver/message/event/EventSchedulerService.java
  axonserver/src/main/java/io/axoniq/axonserver/message/event/ScheduledEventExecutor.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/BaseTaskManager.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/JacksonTaskPayloadSerializer.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/ScheduledTask.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/ScheduledTaskExecutor.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/ScheduledTaskExecutorImpl.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/StandaloneTaskManager.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/Task.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/TaskPayload.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/TaskPayloadSerializer.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/TaskRepository.java
  axonserver/src/main/java/io/axoniq/axonserver/taskscheduler/TransientException.java
  axonserver/src/main/resources/db/migration/V4_0__tasks_update.sql
  axonserver/src/test/java/io/axoniq/axonserver/grpc/CommandServiceTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/FlowControlledStreamObserverTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/PlatformServiceTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/QueryServiceTest.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/SubscriptionQueryITCase.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/heartbeat/HeartbeatMonitorTest.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/LocalEventStorageEngineTest.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/file/InputStreamEventStoreTest.java
  axonserver/src/test/java/io/axoniq/axonserver/localstorage/transaction/SequenceNumberCacheTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/command/CommandCacheTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/command/CommandDispatcherTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/command/CommandRegistrationCacheLoadFactorTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/command/CommandRegistrationCacheTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/event/EventDispatcherTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/event/EventSchedulerServiceTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/event/ScheduledEventExecutorTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/QueryDispatcherTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/subscription/SubscriptionQueryDispatcherTest.java
  axonserver/src/test/java/io/axoniq/axonserver/metric/SlidingWindowTest.java
  axonserver/src/test/java/io/axoniq/axonserver/rest/CommandRestControllerTest.java
  axonserver/src/test/java/io/axoniq/axonserver/rest/QueryRestControllerTest.java
  axonserver/src/test/java/io/axoniq/axonserver/taskscheduler/StandaloneTaskManagerTest.java
  axonserver/src/test/java/io/axoniq/axonserver/util/CountingStreamObserver.java
  axonserver/src/test/java/io/axoniq/axonserver/util/FakeClock.java
  axonserver/src/test/java/io/axoniq/axonserver/util/TestUtils.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Feature
