Repository AxonIQ/axon-server-se, pull requests merged in 2020-05, with the labels that each got.

#121 Added hard and soft bound to flow control queues.
  axonserver/src/main/java/io/axoniq/axonserver/exception/ErrorCode.java
  axonserver/src/main/java/io/axoniq/axonserver/message/FlowControlQueues.java
  axonserver/src/main/java/io/axoniq/axonserver/message/command/CommandDispatcher.java
  axonserver/src/main/java/io/axoniq/axonserver/message/query/QueryDispatcher.java
  axonserver/src/main/java/io/axoniq/axonserver/message/query/QueryHandler.java
  axonserver/src/main/java/io/axoniq/axonserver/metric/BaseMetricName.java
  axonserver/src/test/java/io/axoniq/axonserver/FlowControlQueuesTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/command/CommandDispatcherTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/QueryDispatcherTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#122 Offload expensive data-fetching operations to separate thread pool
  axonserver/src/main/java/io/axoniq/axonserver/config/MessagingPlatformConfiguration.java
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/LocalEventStore.java
Labels: Priority 1: Must, Type: Bug

#125 Fixed IndexManager logging.
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/IndexManager.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#126 Fixed IndexManager logging.
  axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/IndexManager.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#128 Generate coverage data during build
  Jenkinsfile
  pom.xml
Labels: Priority 1: Must, Type: QA
