Repository AxonIQ/axon-server-se, pull requests merged in 2021-03, with the labels that each got.

#252 Correctly handle a FQDN set as hostname in the OS
  axonserver/src/main/java/io/axoniq/axonserver/config/MessagingPlatformConfiguration.java
  axonserver/src/test/java/io/axoniq/axonserver/config/MessagingPlatformConfigurationTest.java
Labels: Priority 2: Should, Type: Feature

#273 Subscription query doesn't unsubscribe in case of no handler exception.
  axonserver/src/main/java/io/axoniq/axonserver/applicationevents/SubscriptionQueryEvents.java
  axonserver/src/main/java/io/axoniq/axonserver/grpc/SubscriptionQueryRequestTarget.java
  axonserver/src/main/java/io/axoniq/axonserver/message/query/subscription/DirectSubscriptionQueries.java
  axonserver/src/main/java/io/axoniq/axonserver/message/query/subscription/SubscriptionQueryDispatcher.java
  axonserver/src/main/java/io/axoniq/axonserver/message/query/subscription/metric/ApplicationSubscriptionMetricRegistry.java
  axonserver/src/main/java/io/axoniq/axonserver/message/query/subscription/metric/GlobalSubscriptionMetricRegistry.java
  axonserver/src/main/java/io/axoniq/axonserver/message/query/subscription/metric/QuerySubscriptionMetricRegistry.java
  axonserver/src/test/java/io/axoniq/axonserver/grpc/SubscriptionQueryRequestTargetTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/subscription/DirectSubscriptionQueriesTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/subscription/SubscriptionQueryDispatcherTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/subscription/metric/ApplicationSubscriptionMetricRegistryTest.java
  axonserver/src/test/java/io/axoniq/axonserver/message/query/subscription/metric/QuerySubscriptionMetricRegistryTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#277 Allow different mode types to enable streaming operations
  axonserver/src/main/java/io/axoniq/axonserver/component/processor/EventProcessor.java
  axonserver/src/main/java/io/axoniq/axonserver/component/processor/EventProcessorMapping.java
  axonserver/src/main/java/io/axoniq/axonserver/component/processor/StreamingProcessor.java
  axonserver/src/main/java/io/axoniq/axonserver/component/processor/StreamingProcessorSegment.java
  axonserver/src/main/java/io/axoniq/axonserver/component/processor/TrackingProcessorSegment.java
  axonserver/src/main/vuejs/components/component/Processors.vue
  axonserver/src/test/java/io/axoniq/axonserver/component/processor/EventProcessorMappingTest.java
  axonserver/src/test/java/io/axoniq/axonserver/component/processor/StreamingProcessorSegmentTest.java
  axonserver/src/test/java/io/axoniq/axonserver/component/processor/StreamingProcessorTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement
